# Generated by Django 3.2.19 on 2023-05-22 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busca_lab', '0002_auto_20230521_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='pc_models',
            field=models.ManyToManyField(related_name='locals', to='busca_lab.PC_model'),
        ),
        migrations.CreateModel(
            name='quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='busca_lab.lab')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='busca_lab.pc_model')),
            ],
        ),
    ]
