# Generated by Django 3.2.19 on 2023-05-22 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busca_lab', '0003_auto_20230521_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='model',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='busca_lab.pc_model'),
        ),
    ]
