# Generated by Django 3.2.19 on 2023-05-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca_lab', '0005_auto_20230522_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='softwares',
            field=models.ManyToManyField(related_name='installed_in', to='busca_lab.Software'),
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='lab',
        ),
        migrations.AddField(
            model_name='quantity',
            name='lab',
            field=models.ManyToManyField(blank=True, related_name='computers', to='busca_lab.Lab'),
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='model',
        ),
        migrations.AddField(
            model_name='quantity',
            name='model',
            field=models.ManyToManyField(blank=True, related_name='quantity', to='busca_lab.PC_model'),
        ),
    ]
