# Generated by Django 3.2.19 on 2023-05-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busca_lab', '0006_auto_20230522_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='model',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='quantity',
        ),
    ]
