# Generated by Django 3.2.19 on 2023-05-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca_lab', '0007_auto_20230522_0151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='pc_models',
        ),
        migrations.AddField(
            model_name='lab',
            name='model',
            field=models.ManyToManyField(blank=True, related_name='locals', to='busca_lab.PC_model'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='softwares',
            field=models.ManyToManyField(blank=True, related_name='installed_in', to='busca_lab.Software'),
        ),
    ]
