# Generated by Django 3.2.19 on 2023-05-22 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busca_lab', '0008_auto_20230522_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qauntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='busca_lab.lab')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='busca_lab.pc_model')),
            ],
        ),
    ]
