# Generated by Django 3.2.19 on 2023-05-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busca_lab', '0009_qauntity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qauntity',
            new_name='Quantity',
        ),
    ]
