# Generated by Django 3.2.19 on 2023-06-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca_lab', '0011_auto_20230602_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('identifier', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
