# Generated by Django 3.2.19 on 2023-06-03 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busca_lab', '0012_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='busca_lab.lab'),
        ),
    ]
