# Generated by Django 3.2.19 on 2023-06-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca_lab', '0013_alter_report_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='problem',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
